//
// Maya/MEL export data written by 3DEqualizer4 Release 4b5
//
// All lengths are in centimeter, all angles are in degree.
//

// create scene group...
string $sceneGroupName = `group -em -name "Scene"`;

// create camera seq_shot_0001_v001_cam_A_LENSED_1_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_A_LENSED_1_1" -hfa 1.306876640419947  -vfa 0.735118110236220 -fl 31.146777935733965 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation -63.287547119941792 -28.466128360075867 182.641941466783890 $cameraTransform;
xform -rotation 13.741545537232398 -28.127799800048763 -12.468438007840545 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 1;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_A_LENSED.0001.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;

// animating camera seq_shot_0001_v001_cam_A_LENSED_1_1...
playbackOptions -min 1 -max 48;

setKeyframe -at translateX -t 1 -v -63.287547119941792 $cameraTransform; setKeyframe -at translateY -t 1 -v -28.466128360075867 $cameraTransform; setKeyframe -at translateZ -t 1 -v 182.641941466783890 $cameraTransform; setKeyframe -at rotateX -t 1 -v 13.741545537232398 $cameraTransform; setKeyframe -at rotateY -t 1 -v -28.127799800048763 $cameraTransform; setKeyframe -at rotateZ -t 1 -v -12.468438007840545 $cameraTransform; setKeyframe -at focalLength -t 1 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 2 -v -62.085115212873305 $cameraTransform; setKeyframe -at translateY -t 2 -v -28.830536192397794 $cameraTransform; setKeyframe -at translateZ -t 2 -v 182.889589762576890 $cameraTransform; setKeyframe -at rotateX -t 2 -v 13.795145974471534 $cameraTransform; setKeyframe -at rotateY -t 2 -v -27.780197352792740 $cameraTransform; setKeyframe -at rotateZ -t 2 -v -12.362284866259337 $cameraTransform; setKeyframe -at focalLength -t 2 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 3 -v -60.530015123484333 $cameraTransform; setKeyframe -at translateY -t 3 -v -29.209967711961902 $cameraTransform; setKeyframe -at translateZ -t 3 -v 183.232480851986710 $cameraTransform; setKeyframe -at rotateX -t 3 -v 13.745979500104511 $cameraTransform; setKeyframe -at rotateY -t 3 -v -27.324730324505179 $cameraTransform; setKeyframe -at rotateZ -t 3 -v -12.090284404774488 $cameraTransform; setKeyframe -at focalLength -t 3 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 4 -v -58.401239592912056 $cameraTransform; setKeyframe -at translateY -t 4 -v -29.625267553957375 $cameraTransform; setKeyframe -at translateZ -t 4 -v 183.730559150571740 $cameraTransform; setKeyframe -at rotateX -t 4 -v 13.604124521446366 $cameraTransform; setKeyframe -at rotateY -t 4 -v -26.690799091969783 $cameraTransform; setKeyframe -at rotateZ -t 4 -v -11.677902267081405 $cameraTransform; setKeyframe -at focalLength -t 4 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 5 -v -55.576675717664457 $cameraTransform; setKeyframe -at translateY -t 5 -v -30.120345922203544 $cameraTransform; setKeyframe -at translateZ -t 5 -v 184.414281808130370 $cameraTransform; setKeyframe -at rotateX -t 5 -v 13.389636224682627 $cameraTransform; setKeyframe -at rotateY -t 5 -v -25.840039200112052 $cameraTransform; setKeyframe -at rotateZ -t 5 -v -11.129293644315043 $cameraTransform; setKeyframe -at focalLength -t 5 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 6 -v -52.023504428253631 $cameraTransform; setKeyframe -at translateY -t 6 -v -30.722819284641890 $cameraTransform; setKeyframe -at translateZ -t 6 -v 185.301760896109100 $cameraTransform; setKeyframe -at rotateX -t 6 -v 13.114123475084522 $cameraTransform; setKeyframe -at rotateY -t 6 -v -24.762294219908860 $cameraTransform; setKeyframe -at rotateZ -t 6 -v -10.451838891821135 $cameraTransform; setKeyframe -at focalLength -t 6 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 7 -v -47.700013506326265 $cameraTransform; setKeyframe -at translateY -t 7 -v -31.484587113014516 $cameraTransform; setKeyframe -at translateZ -t 7 -v 186.388386644742130 $cameraTransform; setKeyframe -at rotateX -t 7 -v 12.778213456823778 $cameraTransform; setKeyframe -at rotateY -t 7 -v -23.451095902213037 $cameraTransform; setKeyframe -at rotateZ -t 7 -v -9.694706360623568 $cameraTransform; setKeyframe -at focalLength -t 7 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 8 -v -42.732906277003295 $cameraTransform; setKeyframe -at translateY -t 8 -v -32.421499251216396 $cameraTransform; setKeyframe -at translateZ -t 8 -v 187.597930000088670 $cameraTransform; setKeyframe -at rotateX -t 8 -v 12.410001334439704 $cameraTransform; setKeyframe -at rotateY -t 8 -v -21.960047332977595 $cameraTransform; setKeyframe -at rotateZ -t 8 -v -8.769157374599800 $cameraTransform; setKeyframe -at focalLength -t 8 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 9 -v -37.402210159208934 $cameraTransform; setKeyframe -at translateY -t 9 -v -33.493437545844486 $cameraTransform; setKeyframe -at translateZ -t 9 -v 188.821166047861570 $cameraTransform; setKeyframe -at rotateX -t 9 -v 11.990911144737822 $cameraTransform; setKeyframe -at rotateY -t 9 -v -20.334638281264425 $cameraTransform; setKeyframe -at rotateZ -t 9 -v -7.910917198430991 $cameraTransform; setKeyframe -at focalLength -t 9 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 10 -v -31.843829055639645 $cameraTransform; setKeyframe -at translateY -t 10 -v -34.674935708887695 $cameraTransform; setKeyframe -at translateZ -t 10 -v 190.007544702385870 $cameraTransform; setKeyframe -at rotateX -t 10 -v 11.526925913004895 $cameraTransform; setKeyframe -at rotateY -t 10 -v -18.636465327814737 $cameraTransform; setKeyframe -at rotateZ -t 10 -v -7.034658559119730 $cameraTransform; setKeyframe -at focalLength -t 10 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 11 -v -26.090025055705603 $cameraTransform; setKeyframe -at translateY -t 11 -v -35.943094513572817 $cameraTransform; setKeyframe -at translateZ -t 11 -v 191.160080084337410 $cameraTransform; setKeyframe -at rotateX -t 11 -v 11.022343223636312 $cameraTransform; setKeyframe -at rotateY -t 11 -v -16.861499895394893 $cameraTransform; setKeyframe -at rotateZ -t 11 -v -6.163313305862675 $cameraTransform; setKeyframe -at focalLength -t 11 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 12 -v -20.134142979648750 $cameraTransform; setKeyframe -at translateY -t 12 -v -37.316003892932130 $cameraTransform; setKeyframe -at translateZ -t 12 -v 192.261708653767930 $cameraTransform; setKeyframe -at rotateX -t 12 -v 10.495006320917708 $cameraTransform; setKeyframe -at rotateY -t 12 -v -15.013832812999032 $cameraTransform; setKeyframe -at rotateZ -t 12 -v -5.324233220186141 $cameraTransform; setKeyframe -at focalLength -t 12 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 13 -v -14.105319183544566 $cameraTransform; setKeyframe -at translateY -t 13 -v -38.779519744007736 $cameraTransform; setKeyframe -at translateZ -t 13 -v 193.220269242754260 $cameraTransform; setKeyframe -at rotateX -t 13 -v 9.970308635176970 $cameraTransform; setKeyframe -at rotateY -t 13 -v -13.110720833249550 $cameraTransform; setKeyframe -at rotateZ -t 13 -v -4.587861462806828 $cameraTransform; setKeyframe -at focalLength -t 13 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 14 -v -8.292190457741015 $cameraTransform; setKeyframe -at translateY -t 14 -v -40.297245397448094 $cameraTransform; setKeyframe -at translateZ -t 14 -v 193.930421147607210 $cameraTransform; setKeyframe -at rotateX -t 14 -v 9.443563806714396 $cameraTransform; setKeyframe -at rotateY -t 14 -v -11.262195569060170 $cameraTransform; setKeyframe -at rotateZ -t 14 -v -3.848905535574222 $cameraTransform; setKeyframe -at focalLength -t 14 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 15 -v -2.906065637604832 $cameraTransform; setKeyframe -at translateY -t 15 -v -41.890289794680633 $cameraTransform; setKeyframe -at translateZ -t 15 -v 194.327673998797390 $cameraTransform; setKeyframe -at rotateX -t 15 -v 8.951993386351138 $cameraTransform; setKeyframe -at rotateY -t 15 -v -9.511461175426451 $cameraTransform; setKeyframe -at rotateZ -t 15 -v -3.141185622550315 $cameraTransform; setKeyframe -at focalLength -t 15 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 16 -v 1.925436943637943 $cameraTransform; setKeyframe -at translateY -t 16 -v -43.439738410979672 $cameraTransform; setKeyframe -at translateZ -t 16 -v 194.442973429847340 $cameraTransform; setKeyframe -at rotateX -t 16 -v 8.511873506962470 $cameraTransform; setKeyframe -at rotateY -t 16 -v -7.897460165161429 $cameraTransform; setKeyframe -at rotateZ -t 16 -v -2.488253725137458 $cameraTransform; setKeyframe -at focalLength -t 16 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 17 -v 6.178378715886554 $cameraTransform; setKeyframe -at translateY -t 17 -v -44.703013572900844 $cameraTransform; setKeyframe -at translateZ -t 17 -v 194.396967571483460 $cameraTransform; setKeyframe -at rotateX -t 17 -v 8.000085706393447 $cameraTransform; setKeyframe -at rotateY -t 17 -v -6.395040182706159 $cameraTransform; setKeyframe -at rotateZ -t 17 -v -1.944989313897180 $cameraTransform; setKeyframe -at focalLength -t 17 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 18 -v 9.785026486125869 $cameraTransform; setKeyframe -at translateY -t 18 -v -45.505646505983478 $cameraTransform; setKeyframe -at translateZ -t 18 -v 194.222485715856950 $cameraTransform; setKeyframe -at rotateX -t 18 -v 7.418797964278063 $cameraTransform; setKeyframe -at rotateY -t 18 -v -5.036157089438581 $cameraTransform; setKeyframe -at rotateZ -t 18 -v -1.455967162500354 $cameraTransform; setKeyframe -at focalLength -t 18 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 19 -v 12.701532570069435 $cameraTransform; setKeyframe -at translateY -t 19 -v -45.864247956725393 $cameraTransform; setKeyframe -at translateZ -t 19 -v 193.896036482202650 $cameraTransform; setKeyframe -at rotateX -t 19 -v 6.801210610772607 $cameraTransform; setKeyframe -at rotateY -t 19 -v -3.820057415573677 $cameraTransform; setKeyframe -at rotateZ -t 19 -v -1.016416559763985 $cameraTransform; setKeyframe -at focalLength -t 19 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 20 -v 14.992503255950892 $cameraTransform; setKeyframe -at translateY -t 20 -v -45.854275764815270 $cameraTransform; setKeyframe -at translateZ -t 20 -v 193.429527739529360 $cameraTransform; setKeyframe -at rotateX -t 20 -v 6.187697784336057 $cameraTransform; setKeyframe -at rotateY -t 20 -v -2.728223057343066 $cameraTransform; setKeyframe -at rotateZ -t 20 -v -0.646083491100821 $cameraTransform; setKeyframe -at focalLength -t 20 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 21 -v 16.657199414935651 $cameraTransform; setKeyframe -at translateY -t 21 -v -45.381468365107771 $cameraTransform; setKeyframe -at translateZ -t 21 -v 192.808917780956140 $cameraTransform; setKeyframe -at rotateX -t 21 -v 5.581540592922162 $cameraTransform; setKeyframe -at rotateY -t 21 -v -1.796902921719178 $cameraTransform; setKeyframe -at rotateZ -t 21 -v -0.356308644325080 $cameraTransform; setKeyframe -at focalLength -t 21 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 22 -v 17.833177986266119 $cameraTransform; setKeyframe -at translateY -t 22 -v -44.401513818999518 $cameraTransform; setKeyframe -at translateZ -t 22 -v 192.036372810100800 $cameraTransform; setKeyframe -at rotateX -t 22 -v 4.972827358285326 $cameraTransform; setKeyframe -at rotateY -t 22 -v -1.039530428440183 $cameraTransform; setKeyframe -at rotateZ -t 22 -v -0.192683686617198 $cameraTransform; setKeyframe -at focalLength -t 22 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 23 -v 18.662221363010815 $cameraTransform; setKeyframe -at translateY -t 23 -v -42.914202803799284 $cameraTransform; setKeyframe -at translateZ -t 23 -v 191.092043473551430 $cameraTransform; setKeyframe -at rotateX -t 23 -v 4.315202065473161 $cameraTransform; setKeyframe -at rotateY -t 23 -v -0.395330726926362 $cameraTransform; setKeyframe -at rotateZ -t 23 -v -0.042128961618565 $cameraTransform; setKeyframe -at focalLength -t 23 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 24 -v 19.102181235128722 $cameraTransform; setKeyframe -at translateY -t 24 -v -40.846126555616621 $cameraTransform; setKeyframe -at translateZ -t 24 -v 189.932107735678730 $cameraTransform; setKeyframe -at rotateX -t 24 -v 3.595229187047725 $cameraTransform; setKeyframe -at rotateY -t 24 -v 0.117152944697348 $cameraTransform; setKeyframe -at rotateZ -t 24 -v 0.075982894167681 $cameraTransform; setKeyframe -at focalLength -t 24 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 25 -v 19.256308995995372 $cameraTransform; setKeyframe -at translateY -t 25 -v -38.316685621283298 $cameraTransform; setKeyframe -at translateZ -t 25 -v 188.617081878797880 $cameraTransform; setKeyframe -at rotateX -t 25 -v 2.838854450277760 $cameraTransform; setKeyframe -at rotateY -t 25 -v 0.531176903575390 $cameraTransform; setKeyframe -at rotateZ -t 25 -v 0.151086980063540 $cameraTransform; setKeyframe -at focalLength -t 25 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 26 -v 19.142950395192884 $cameraTransform; setKeyframe -at translateY -t 26 -v -35.391905291812968 $cameraTransform; setKeyframe -at translateZ -t 26 -v 187.178854256357480 $cameraTransform; setKeyframe -at rotateX -t 26 -v 2.058564218204029 $cameraTransform; setKeyframe -at rotateY -t 26 -v 0.851523499654515 $cameraTransform; setKeyframe -at rotateZ -t 26 -v 0.189818901310934 $cameraTransform; setKeyframe -at focalLength -t 26 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 27 -v 18.734277758424767 $cameraTransform; setKeyframe -at translateY -t 27 -v -32.079498567050805 $cameraTransform; setKeyframe -at translateZ -t 27 -v 185.613503007400650 $cameraTransform; setKeyframe -at rotateX -t 27 -v 1.248867377674784 $cameraTransform; setKeyframe -at rotateY -t 27 -v 1.069468080133484 $cameraTransform; setKeyframe -at rotateZ -t 27 -v 0.198206505794134 $cameraTransform; setKeyframe -at focalLength -t 27 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 28 -v 18.157902249238838 $cameraTransform; setKeyframe -at translateY -t 28 -v -28.510677920692984 $cameraTransform; setKeyframe -at translateZ -t 28 -v 183.964264898657430 $cameraTransform; setKeyframe -at rotateX -t 28 -v 0.442569546763313 $cameraTransform; setKeyframe -at rotateY -t 28 -v 1.230693261804687 $cameraTransform; setKeyframe -at rotateZ -t 28 -v 0.169462702555461 $cameraTransform; setKeyframe -at focalLength -t 28 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 29 -v 17.423302458373481 $cameraTransform; setKeyframe -at translateY -t 29 -v -24.666436670722117 $cameraTransform; setKeyframe -at translateZ -t 29 -v 182.234589099222690 $cameraTransform; setKeyframe -at rotateX -t 29 -v -0.376566904960257 $cameraTransform; setKeyframe -at rotateY -t 29 -v 1.340900105661814 $cameraTransform; setKeyframe -at rotateZ -t 29 -v 0.107383807451458 $cameraTransform; setKeyframe -at focalLength -t 29 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 30 -v 16.493080211484230 $cameraTransform; setKeyframe -at translateY -t 30 -v -20.512042408244234 $cameraTransform; setKeyframe -at translateZ -t 30 -v 180.422511024446070 $cameraTransform; setKeyframe -at rotateX -t 30 -v -1.223326753808584 $cameraTransform; setKeyframe -at rotateY -t 30 -v 1.374713169777269 $cameraTransform; setKeyframe -at rotateZ -t 30 -v 0.057373504066752 $cameraTransform; setKeyframe -at focalLength -t 30 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 31 -v 15.337287421472732 $cameraTransform; setKeyframe -at translateY -t 31 -v -16.083636199447795 $cameraTransform; setKeyframe -at translateZ -t 31 -v 178.530339087953650 $cameraTransform; setKeyframe -at rotateX -t 31 -v -2.102547503306198 $cameraTransform; setKeyframe -at rotateY -t 31 -v 1.352338356497788 $cameraTransform; setKeyframe -at rotateZ -t 31 -v -0.058298330048873 $cameraTransform; setKeyframe -at focalLength -t 31 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 32 -v 13.952209131808967 $cameraTransform; setKeyframe -at translateY -t 32 -v -11.437506612487445 $cameraTransform; setKeyframe -at translateZ -t 32 -v 176.562077551953370 $cameraTransform; setKeyframe -at rotateX -t 32 -v -3.008643975858352 $cameraTransform; setKeyframe -at rotateY -t 32 -v 1.275067794107519 $cameraTransform; setKeyframe -at rotateZ -t 32 -v -0.194479339248051 $cameraTransform; setKeyframe -at focalLength -t 32 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 33 -v 12.426870456940090 $cameraTransform; setKeyframe -at translateY -t 33 -v -6.700212540585839 $cameraTransform; setKeyframe -at translateZ -t 33 -v 174.547893287889540 $cameraTransform; setKeyframe -at rotateX -t 33 -v -3.898551938990064 $cameraTransform; setKeyframe -at rotateY -t 33 -v 1.131637809388446 $cameraTransform; setKeyframe -at rotateZ -t 33 -v -0.357219495338123 $cameraTransform; setKeyframe -at focalLength -t 33 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 34 -v 10.813234463126735 $cameraTransform; setKeyframe -at translateY -t 34 -v -1.945583124334139 $cameraTransform; setKeyframe -at translateZ -t 34 -v 172.507514216260380 $cameraTransform; setKeyframe -at rotateX -t 34 -v -4.765209446465099 $cameraTransform; setKeyframe -at rotateY -t 34 -v 0.949862854690961 $cameraTransform; setKeyframe -at rotateZ -t 34 -v -0.549096639778433 $cameraTransform; setKeyframe -at focalLength -t 34 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 35 -v 9.123473595655582 $cameraTransform; setKeyframe -at translateY -t 35 -v 2.765391869116097 $cameraTransform; setKeyframe -at translateZ -t 35 -v 170.464260083834380 $cameraTransform; setKeyframe -at rotateX -t 35 -v -5.590434863578704 $cameraTransform; setKeyframe -at rotateY -t 35 -v 0.748454061350386 $cameraTransform; setKeyframe -at rotateZ -t 35 -v -0.699826868607932 $cameraTransform; setKeyframe -at focalLength -t 35 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 36 -v 7.369507115708758 $cameraTransform; setKeyframe -at translateY -t 36 -v 7.368339539135784 $cameraTransform; setKeyframe -at translateZ -t 36 -v 168.429352767369320 $cameraTransform; setKeyframe -at rotateX -t 36 -v -6.379295757841774 $cameraTransform; setKeyframe -at rotateY -t 36 -v 0.524684319193437 $cameraTransform; setKeyframe -at rotateZ -t 36 -v -0.892841732995564 $cameraTransform; setKeyframe -at focalLength -t 36 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 37 -v 5.596551829308631 $cameraTransform; setKeyframe -at translateY -t 37 -v 11.808024021380465 $cameraTransform; setKeyframe -at translateZ -t 37 -v 166.431396904903720 $cameraTransform; setKeyframe -at rotateX -t 37 -v -7.114086453960688 $cameraTransform; setKeyframe -at rotateY -t 37 -v 0.290365833465947 $cameraTransform; setKeyframe -at rotateZ -t 37 -v -1.093485041717799 $cameraTransform; setKeyframe -at focalLength -t 37 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 38 -v 3.903334641288919 $cameraTransform; setKeyframe -at translateY -t 38 -v 15.997788669109593 $cameraTransform; setKeyframe -at translateZ -t 38 -v 164.551364102128870 $cameraTransform; setKeyframe -at rotateX -t 38 -v -7.772603192490742 $cameraTransform; setKeyframe -at rotateY -t 38 -v 0.075757363568296 $cameraTransform; setKeyframe -at rotateZ -t 38 -v -1.311023912334563 $cameraTransform; setKeyframe -at focalLength -t 38 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 39 -v 2.345988900680547 $cameraTransform; setKeyframe -at translateY -t 39 -v 19.954411240935826 $cameraTransform; setKeyframe -at translateZ -t 39 -v 162.836418623462750 $cameraTransform; setKeyframe -at rotateX -t 39 -v -8.370529392281467 $cameraTransform; setKeyframe -at rotateY -t 39 -v -0.099394019041653 $cameraTransform; setKeyframe -at rotateZ -t 39 -v -1.533349061923726 $cameraTransform; setKeyframe -at focalLength -t 39 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 40 -v 0.966252127642164 $cameraTransform; setKeyframe -at translateY -t 40 -v 23.673532781487907 $cameraTransform; setKeyframe -at translateZ -t 40 -v 161.314289345493390 $cameraTransform; setKeyframe -at rotateX -t 40 -v -8.965735949701779 $cameraTransform; setKeyframe -at rotateY -t 40 -v -0.203551303492066 $cameraTransform; setKeyframe -at rotateZ -t 40 -v -1.769681895527219 $cameraTransform; setKeyframe -at focalLength -t 40 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 41 -v -0.232513183741928 $cameraTransform; setKeyframe -at translateY -t 41 -v 27.192839681654210 $cameraTransform; setKeyframe -at translateZ -t 41 -v 159.975766208260070 $cameraTransform; setKeyframe -at rotateX -t 41 -v -9.498548316173570 $cameraTransform; setKeyframe -at rotateY -t 41 -v -0.276141359607023 $cameraTransform; setKeyframe -at rotateZ -t 41 -v -1.998096183176934 $cameraTransform; setKeyframe -at focalLength -t 41 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 42 -v -1.263840662945179 $cameraTransform; setKeyframe -at translateY -t 42 -v 30.593290710125572 $cameraTransform; setKeyframe -at translateZ -t 42 -v 158.799725240652290 $cameraTransform; setKeyframe -at rotateX -t 42 -v -10.042652140824863 $cameraTransform; setKeyframe -at rotateY -t 42 -v -0.309176993386703 $cameraTransform; setKeyframe -at rotateZ -t 42 -v -2.210025504164343 $cameraTransform; setKeyframe -at focalLength -t 42 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 43 -v -2.126788445437701 $cameraTransform; setKeyframe -at translateY -t 43 -v 33.733478880571489 $cameraTransform; setKeyframe -at translateZ -t 43 -v 157.780708385614640 $cameraTransform; setKeyframe -at rotateX -t 43 -v -10.599207465932800 $cameraTransform; setKeyframe -at rotateY -t 43 -v -0.338147157331743 $cameraTransform; setKeyframe -at rotateZ -t 43 -v -2.376897994376148 $cameraTransform; setKeyframe -at focalLength -t 43 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 44 -v -2.882027036865816 $cameraTransform; setKeyframe -at translateY -t 44 -v 36.420489306816201 $cameraTransform; setKeyframe -at translateZ -t 44 -v 156.857840773388230 $cameraTransform; setKeyframe -at rotateX -t 44 -v -11.059789562548612 $cameraTransform; setKeyframe -at rotateY -t 44 -v -0.342163797931743 $cameraTransform; setKeyframe -at rotateZ -t 44 -v -2.521182043175843 $cameraTransform; setKeyframe -at focalLength -t 44 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 45 -v -3.561528769323856 $cameraTransform; setKeyframe -at translateY -t 45 -v 38.574862340777869 $cameraTransform; setKeyframe -at translateZ -t 45 -v 156.010653491755620 $cameraTransform; setKeyframe -at rotateX -t 45 -v -11.424468957830673 $cameraTransform; setKeyframe -at rotateY -t 45 -v -0.361228343449952 $cameraTransform; setKeyframe -at rotateZ -t 45 -v -2.595727414660279 $cameraTransform; setKeyframe -at focalLength -t 45 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 46 -v -4.111927891489789 $cameraTransform; setKeyframe -at translateY -t 46 -v 40.197672236676297 $cameraTransform; setKeyframe -at translateZ -t 46 -v 155.310532151413610 $cameraTransform; setKeyframe -at rotateX -t 46 -v -11.700758412476539 $cameraTransform; setKeyframe -at rotateY -t 46 -v -0.373034184118799 $cameraTransform; setKeyframe -at rotateZ -t 46 -v -2.676947064694971 $cameraTransform; setKeyframe -at focalLength -t 46 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 47 -v -4.505834662984870 $cameraTransform; setKeyframe -at translateY -t 47 -v 41.401860046852072 $cameraTransform; setKeyframe -at translateZ -t 47 -v 154.796451381930350 $cameraTransform; setKeyframe -at rotateX -t 47 -v -11.952765317896420 $cameraTransform; setKeyframe -at rotateY -t 47 -v -0.388262391349570 $cameraTransform; setKeyframe -at rotateZ -t 47 -v -2.712018327947733 $cameraTransform; setKeyframe -at focalLength -t 47 -v 31.146777935733965 $cameraShape;
setKeyframe -at translateX -t 48 -v -4.786389674284826 $cameraTransform; setKeyframe -at translateY -t 48 -v 42.350531446142625 $cameraTransform; setKeyframe -at translateZ -t 48 -v 154.423009318145600 $cameraTransform; setKeyframe -at rotateX -t 48 -v -12.269534578257279 $cameraTransform; setKeyframe -at rotateY -t 48 -v -0.455166532615412 $cameraTransform; setKeyframe -at rotateZ -t 48 -v -2.699749156735001 $cameraTransform; setKeyframe -at focalLength -t 48 -v 31.146777935733965 $cameraShape;

// create camera seq_shot_0001_v001_cam_B_LENSED_2_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_B_LENSED_2_1" -hfa 1.045501312335958  -vfa 0.735118110236220 -fl 13.712807770386641 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation 57.131639903850370 42.282124262836049 49.136332563277243 $cameraTransform;
xform -rotation -26.177226482384192 24.323258221755275 13.239008038665760 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 1;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_B_LENSED.0001.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;

// animating camera seq_shot_0001_v001_cam_B_LENSED_2_1...
playbackOptions -min 1 -max 48;

setKeyframe -at translateX -t 1 -v 57.131639903850370 $cameraTransform; setKeyframe -at translateY -t 1 -v 42.282124262836049 $cameraTransform; setKeyframe -at translateZ -t 1 -v 49.136332563277243 $cameraTransform; setKeyframe -at rotateX -t 1 -v -26.177226482384192 $cameraTransform; setKeyframe -at rotateY -t 1 -v 24.323258221755275 $cameraTransform; setKeyframe -at rotateZ -t 1 -v 13.239008038665760 $cameraTransform; setKeyframe -at focalLength -t 1 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 2 -v 56.447632374821623 $cameraTransform; setKeyframe -at translateY -t 2 -v 42.303694885352371 $cameraTransform; setKeyframe -at translateZ -t 2 -v 49.087664919620060 $cameraTransform; setKeyframe -at rotateX -t 2 -v -26.377942335151889 $cameraTransform; setKeyframe -at rotateY -t 2 -v 23.892248842301445 $cameraTransform; setKeyframe -at rotateZ -t 2 -v 13.301720830010586 $cameraTransform; setKeyframe -at focalLength -t 2 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 3 -v 55.496058860309091 $cameraTransform; setKeyframe -at translateY -t 3 -v 42.362235318346599 $cameraTransform; setKeyframe -at translateZ -t 3 -v 49.015664546956422 $cameraTransform; setKeyframe -at rotateX -t 3 -v -26.756091218439728 $cameraTransform; setKeyframe -at rotateY -t 3 -v 23.443140795665716 $cameraTransform; setKeyframe -at rotateZ -t 3 -v 13.195652905565936 $cameraTransform; setKeyframe -at focalLength -t 3 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 4 -v 54.125032074959925 $cameraTransform; setKeyframe -at translateY -t 4 -v 42.470057266603035 $cameraTransform; setKeyframe -at translateZ -t 4 -v 48.907317016298215 $cameraTransform; setKeyframe -at rotateX -t 4 -v -27.354632095281250 $cameraTransform; setKeyframe -at rotateY -t 4 -v 22.847237052121965 $cameraTransform; setKeyframe -at rotateZ -t 4 -v 12.967176199145081 $cameraTransform; setKeyframe -at focalLength -t 4 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 5 -v 52.285090981076706 $cameraTransform; setKeyframe -at translateY -t 5 -v 42.615375832209509 $cameraTransform; setKeyframe -at translateZ -t 5 -v 48.761901702527993 $cameraTransform; setKeyframe -at rotateX -t 5 -v -28.153169324894531 $cameraTransform; setKeyframe -at rotateY -t 5 -v 22.067117878725050 $cameraTransform; setKeyframe -at rotateZ -t 5 -v 12.656001144970599 $cameraTransform; setKeyframe -at focalLength -t 5 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 6 -v 50.022908668817891 $cameraTransform; setKeyframe -at translateY -t 6 -v 42.777128915456998 $cameraTransform; setKeyframe -at translateZ -t 6 -v 48.589900837549244 $cameraTransform; setKeyframe -at rotateX -t 6 -v -29.121711814189290 $cameraTransform; setKeyframe -at rotateY -t 6 -v 21.105513775226459 $cameraTransform; setKeyframe -at rotateZ -t 6 -v 12.248154787725735 $cameraTransform; setKeyframe -at focalLength -t 6 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 7 -v 47.360611324809341 $cameraTransform; setKeyframe -at translateY -t 7 -v 42.952669615130723 $cameraTransform; setKeyframe -at translateZ -t 7 -v 48.398763953743959 $cameraTransform; setKeyframe -at rotateX -t 7 -v -30.230569465885580 $cameraTransform; setKeyframe -at rotateY -t 7 -v 20.002627663522507 $cameraTransform; setKeyframe -at rotateZ -t 7 -v 11.775947960223663 $cameraTransform; setKeyframe -at focalLength -t 7 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 8 -v 44.339961706167642 $cameraTransform; setKeyframe -at translateY -t 8 -v 43.149135557126662 $cameraTransform; setKeyframe -at translateZ -t 8 -v 48.191697610783713 $cameraTransform; setKeyframe -at rotateX -t 8 -v -31.472467192870930 $cameraTransform; setKeyframe -at rotateY -t 8 -v 18.736796566567023 $cameraTransform; setKeyframe -at rotateZ -t 8 -v 11.264612878626371 $cameraTransform; setKeyframe -at focalLength -t 8 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 9 -v 41.024663965710737 $cameraTransform; setKeyframe -at translateY -t 9 -v 43.367234232279046 $cameraTransform; setKeyframe -at translateZ -t 9 -v 47.974656711282094 $cameraTransform; setKeyframe -at rotateX -t 9 -v -32.838254455554768 $cameraTransform; setKeyframe -at rotateY -t 9 -v 17.385865587903901 $cameraTransform; setKeyframe -at rotateZ -t 9 -v 10.705637202463825 $cameraTransform; setKeyframe -at focalLength -t 9 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 10 -v 37.414556010114232 $cameraTransform; setKeyframe -at translateY -t 10 -v 43.602960063698291 $cameraTransform; setKeyframe -at translateZ -t 10 -v 47.754231000018457 $cameraTransform; setKeyframe -at rotateX -t 10 -v -34.321281425210380 $cameraTransform; setKeyframe -at rotateY -t 10 -v 15.923482069274522 $cameraTransform; setKeyframe -at rotateZ -t 10 -v 10.067775163606909 $cameraTransform; setKeyframe -at focalLength -t 10 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 11 -v 33.565571452329102 $cameraTransform; setKeyframe -at translateY -t 11 -v 43.841260081573353 $cameraTransform; setKeyframe -at translateZ -t 11 -v 47.530955306594365 $cameraTransform; setKeyframe -at rotateX -t 11 -v -35.859603339277569 $cameraTransform; setKeyframe -at rotateY -t 11 -v 14.382946168237389 $cameraTransform; setKeyframe -at rotateZ -t 11 -v 9.370029230193318 $cameraTransform; setKeyframe -at focalLength -t 11 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 12 -v 29.559469539604905 $cameraTransform; setKeyframe -at translateY -t 12 -v 44.069970955690913 $cameraTransform; setKeyframe -at translateZ -t 12 -v 47.291132224559043 $cameraTransform; setKeyframe -at rotateX -t 12 -v -37.445307359974720 $cameraTransform; setKeyframe -at rotateY -t 12 -v 12.796863214170889 $cameraTransform; setKeyframe -at rotateZ -t 12 -v 8.685824860162148 $cameraTransform; setKeyframe -at focalLength -t 12 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 13 -v 25.473003670588486 $cameraTransform; setKeyframe -at translateY -t 13 -v 44.282616833264711 $cameraTransform; setKeyframe -at translateZ -t 13 -v 47.025298782941505 $cameraTransform; setKeyframe -at rotateX -t 13 -v -39.073724371301822 $cameraTransform; setKeyframe -at rotateY -t 13 -v 11.226188370283115 $cameraTransform; setKeyframe -at rotateZ -t 13 -v 7.954207107264507 $cameraTransform; setKeyframe -at focalLength -t 13 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 14 -v 21.412068942306071 $cameraTransform; setKeyframe -at translateY -t 14 -v 44.468720494641609 $cameraTransform; setKeyframe -at translateZ -t 14 -v 46.744937435327380 $cameraTransform; setKeyframe -at rotateX -t 14 -v -40.637502117772094 $cameraTransform; setKeyframe -at rotateY -t 14 -v 9.758395440710482 $cameraTransform; setKeyframe -at rotateZ -t 14 -v 7.153654301870514 $cameraTransform; setKeyframe -at focalLength -t 14 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 15 -v 17.423673041217160 $cameraTransform; setKeyframe -at translateY -t 15 -v 44.617788806655533 $cameraTransform; setKeyframe -at translateZ -t 15 -v 46.467302682246292 $cameraTransform; setKeyframe -at rotateX -t 15 -v -42.111657198487407 $cameraTransform; setKeyframe -at rotateY -t 15 -v 8.356044781887228 $cameraTransform; setKeyframe -at rotateZ -t 15 -v 6.307099085843920 $cameraTransform; setKeyframe -at focalLength -t 15 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 16 -v 13.546128049193861 $cameraTransform; setKeyframe -at translateY -t 16 -v 44.722215337442833 $cameraTransform; setKeyframe -at translateZ -t 16 -v 46.195131995464941 $cameraTransform; setKeyframe -at rotateX -t 16 -v -43.527720673536166 $cameraTransform; setKeyframe -at rotateY -t 16 -v 7.057145684013297 $cameraTransform; setKeyframe -at rotateZ -t 16 -v 5.399391452511761 $cameraTransform; setKeyframe -at focalLength -t 16 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 17 -v 9.820179044181762 $cameraTransform; setKeyframe -at translateY -t 17 -v 44.785655134243662 $cameraTransform; setKeyframe -at translateZ -t 17 -v 45.926201961285322 $cameraTransform; setKeyframe -at rotateX -t 17 -v -44.805726931928206 $cameraTransform; setKeyframe -at rotateY -t 17 -v 5.801888688857628 $cameraTransform; setKeyframe -at rotateZ -t 17 -v 4.550411267260550 $cameraTransform; setKeyframe -at focalLength -t 17 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 18 -v 6.333417897722806 $cameraTransform; setKeyframe -at translateY -t 18 -v 44.808269878100965 $cameraTransform; setKeyframe -at translateZ -t 18 -v 45.687659966050404 $cameraTransform; setKeyframe -at rotateX -t 18 -v -45.934564789680557 $cameraTransform; setKeyframe -at rotateY -t 18 -v 4.651642619360939 $cameraTransform; setKeyframe -at rotateZ -t 18 -v 3.577421223157559 $cameraTransform; setKeyframe -at focalLength -t 18 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 19 -v 3.188159734708943 $cameraTransform; setKeyframe -at translateY -t 19 -v 44.804534946269264 $cameraTransform; setKeyframe -at translateZ -t 19 -v 45.520202795732189 $cameraTransform; setKeyframe -at rotateX -t 19 -v -46.914882495029921 $cameraTransform; setKeyframe -at rotateY -t 19 -v 3.833776464648035 $cameraTransform; setKeyframe -at rotateZ -t 19 -v 2.499147748601486 $cameraTransform; setKeyframe -at focalLength -t 19 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 20 -v 0.410521128202187 $cameraTransform; setKeyframe -at translateY -t 20 -v 44.792552629789931 $cameraTransform; setKeyframe -at translateZ -t 20 -v 45.438860967097938 $cameraTransform; setKeyframe -at rotateX -t 20 -v -47.655466284343490 $cameraTransform; setKeyframe -at rotateY -t 20 -v 3.172499923631619 $cameraTransform; setKeyframe -at rotateZ -t 20 -v 1.410851344076233 $cameraTransform; setKeyframe -at focalLength -t 20 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 21 -v -1.996290270602731 $cameraTransform; setKeyframe -at translateY -t 21 -v 44.737316155664573 $cameraTransform; setKeyframe -at translateZ -t 21 -v 45.435435835861483 $cameraTransform; setKeyframe -at rotateX -t 21 -v -48.146435475579381 $cameraTransform; setKeyframe -at rotateY -t 21 -v 2.619210992656244 $cameraTransform; setKeyframe -at rotateZ -t 21 -v 0.353121398548949 $cameraTransform; setKeyframe -at focalLength -t 21 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 22 -v -4.109567112232468 $cameraTransform; setKeyframe -at translateY -t 22 -v 44.599262011784241 $cameraTransform; setKeyframe -at translateZ -t 22 -v 45.484581087422100 $cameraTransform; setKeyframe -at rotateX -t 22 -v -48.321600081964974 $cameraTransform; setKeyframe -at rotateY -t 22 -v 2.025184097365949 $cameraTransform; setKeyframe -at rotateZ -t 22 -v -0.559677756142687 $cameraTransform; setKeyframe -at focalLength -t 22 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 23 -v -6.037167663276295 $cameraTransform; setKeyframe -at translateY -t 23 -v 44.345960940530446 $cameraTransform; setKeyframe -at translateZ -t 23 -v 45.544898373807030 $cameraTransform; setKeyframe -at rotateX -t 23 -v -48.176270097115690 $cameraTransform; setKeyframe -at rotateY -t 23 -v 1.382966138199910 $cameraTransform; setKeyframe -at rotateZ -t 23 -v -1.400840499876779 $cameraTransform; setKeyframe -at focalLength -t 23 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 24 -v -7.832176070195745 $cameraTransform; setKeyframe -at translateY -t 24 -v 43.931189066945009 $cameraTransform; setKeyframe -at translateZ -t 24 -v 45.573833506917396 $cameraTransform; setKeyframe -at rotateX -t 24 -v -47.721487377003470 $cameraTransform; setKeyframe -at rotateY -t 24 -v 0.811035308644561 $cameraTransform; setKeyframe -at rotateZ -t 24 -v -2.350025289954445 $cameraTransform; setKeyframe -at focalLength -t 24 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 25 -v -9.583131361227117 $cameraTransform; setKeyframe -at translateY -t 25 -v 43.363135981007744 $cameraTransform; setKeyframe -at translateZ -t 25 -v 45.551330375102147 $cameraTransform; setKeyframe -at rotateX -t 25 -v -47.006121326327921 $cameraTransform; setKeyframe -at rotateY -t 25 -v 0.192500934481934 $cameraTransform; setKeyframe -at rotateZ -t 25 -v -3.328781238763477 $cameraTransform; setKeyframe -at focalLength -t 25 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 26 -v -11.311475387417211 $cameraTransform; setKeyframe -at translateY -t 26 -v 42.641706417759266 $cameraTransform; setKeyframe -at translateZ -t 26 -v 45.478476116416971 $cameraTransform; setKeyframe -at rotateX -t 26 -v -46.040906036852974 $cameraTransform; setKeyframe -at rotateY -t 26 -v -0.513653224489389 $cameraTransform; setKeyframe -at rotateZ -t 26 -v -4.295518891986555 $cameraTransform; setKeyframe -at focalLength -t 26 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 27 -v -13.000002611258367 $cameraTransform; setKeyframe -at translateY -t 27 -v 41.754472091381238 $cameraTransform; setKeyframe -at translateZ -t 27 -v 45.359401365852094 $cameraTransform; setKeyframe -at rotateX -t 27 -v -44.832331785135992 $cameraTransform; setKeyframe -at rotateY -t 27 -v -1.316815079352118 $cameraTransform; setKeyframe -at rotateZ -t 27 -v -5.225083398135992 $cameraTransform; setKeyframe -at focalLength -t 27 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 28 -v -14.672862902423264 $cameraTransform; setKeyframe -at translateY -t 28 -v 40.736986116188014 $cameraTransform; setKeyframe -at translateZ -t 28 -v 45.201101811111293 $cameraTransform; setKeyframe -at rotateX -t 28 -v -43.417069016642337 $cameraTransform; setKeyframe -at rotateY -t 28 -v -2.230837414873566 $cameraTransform; setKeyframe -at rotateZ -t 28 -v -6.097179004695458 $cameraTransform; setKeyframe -at focalLength -t 28 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 29 -v -16.312210163072589 $cameraTransform; setKeyframe -at translateY -t 29 -v 39.605254115742014 $cameraTransform; setKeyframe -at translateZ -t 29 -v 45.003195446660413 $cameraTransform; setKeyframe -at rotateX -t 29 -v -41.840778586574778 $cameraTransform; setKeyframe -at rotateY -t 29 -v -3.226742232369628 $cameraTransform; setKeyframe -at rotateZ -t 29 -v -6.980680784056212 $cameraTransform; setKeyframe -at focalLength -t 29 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 30 -v -17.909499467267718 $cameraTransform; setKeyframe -at translateY -t 30 -v 38.380303196906873 $cameraTransform; setKeyframe -at translateZ -t 30 -v 44.764118261508401 $cameraTransform; setKeyframe -at rotateX -t 30 -v -40.131977970766719 $cameraTransform; setKeyframe -at rotateY -t 30 -v -4.330300356772156 $cameraTransform; setKeyframe -at rotateZ -t 30 -v -7.788331320389954 $cameraTransform; setKeyframe -at focalLength -t 30 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 31 -v -19.473487634273116 $cameraTransform; setKeyframe -at translateY -t 31 -v 37.091459432012570 $cameraTransform; setKeyframe -at translateZ -t 31 -v 44.490852016757955 $cameraTransform; setKeyframe -at rotateX -t 31 -v -38.320025475554672 $cameraTransform; setKeyframe -at rotateY -t 31 -v -5.540693377822006 $cameraTransform; setKeyframe -at rotateZ -t 31 -v -8.519000809429063 $cameraTransform; setKeyframe -at focalLength -t 31 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 32 -v -20.991316527242862 $cameraTransform; setKeyframe -at translateY -t 32 -v 35.750115260151858 $cameraTransform; setKeyframe -at translateZ -t 32 -v 44.191286612245023 $cameraTransform; setKeyframe -at rotateX -t 32 -v -36.425856649923915 $cameraTransform; setKeyframe -at rotateY -t 32 -v -6.831789476270327 $cameraTransform; setKeyframe -at rotateZ -t 32 -v -9.210320903075619 $cameraTransform; setKeyframe -at focalLength -t 32 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 33 -v -22.452522734569932 $cameraTransform; setKeyframe -at translateY -t 33 -v 34.393553483408745 $cameraTransform; setKeyframe -at translateZ -t 33 -v 43.880111227029779 $cameraTransform; setKeyframe -at rotateX -t 33 -v -34.517622830325493 $cameraTransform; setKeyframe -at rotateY -t 33 -v -8.180915592023768 $cameraTransform; setKeyframe -at rotateZ -t 33 -v -9.819254349854010 $cameraTransform; setKeyframe -at focalLength -t 33 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 34 -v -23.848039196466289 $cameraTransform; setKeyframe -at translateY -t 34 -v 33.060852128893124 $cameraTransform; setKeyframe -at translateZ -t 34 -v 43.570655961954671 $cameraTransform; setKeyframe -at rotateX -t 34 -v -32.586428658530508 $cameraTransform; setKeyframe -at rotateY -t 34 -v -9.567991412379220 $cameraTransform; setKeyframe -at rotateZ -t 34 -v -10.403426828219828 $cameraTransform; setKeyframe -at focalLength -t 34 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 35 -v -25.171406500416452 $cameraTransform; setKeyframe -at translateY -t 35 -v 31.758321140379806 $cameraTransform; setKeyframe -at translateZ -t 35 -v 43.266474228395516 $cameraTransform; setKeyframe -at rotateX -t 35 -v -30.824874487818331 $cameraTransform; setKeyframe -at rotateY -t 35 -v -10.929844864228636 $cameraTransform; setKeyframe -at rotateZ -t 35 -v -10.768240732671334 $cameraTransform; setKeyframe -at focalLength -t 35 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 36 -v -26.433375481579336 $cameraTransform; setKeyframe -at translateY -t 36 -v 30.460644724599938 $cameraTransform; setKeyframe -at translateZ -t 36 -v 42.969245878191735 $cameraTransform; setKeyframe -at rotateX -t 36 -v -28.975283054448898 $cameraTransform; setKeyframe -at rotateY -t 36 -v -12.320828993664062 $cameraTransform; setKeyframe -at rotateZ -t 36 -v -11.247377186243906 $cameraTransform; setKeyframe -at focalLength -t 36 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 37 -v -27.637328601985718 $cameraTransform; setKeyframe -at translateY -t 37 -v 29.153886789015413 $cameraTransform; setKeyframe -at translateZ -t 37 -v 42.678246809880605 $cameraTransform; setKeyframe -at rotateX -t 37 -v -27.109167336382914 $cameraTransform; setKeyframe -at rotateY -t 37 -v -13.733445586514792 $cameraTransform; setKeyframe -at rotateZ -t 37 -v -11.579754164599940 $cameraTransform; setKeyframe -at focalLength -t 37 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 38 -v -28.768812497840567 $cameraTransform; setKeyframe -at translateY -t 38 -v 27.864215939073983 $cameraTransform; setKeyframe -at translateZ -t 38 -v 42.392489127916065 $cameraTransform; setKeyframe -at rotateX -t 38 -v -25.291452128700989 $cameraTransform; setKeyframe -at rotateY -t 38 -v -15.117250418905854 $cameraTransform; setKeyframe -at rotateZ -t 38 -v -12.003880189496195 $cameraTransform; setKeyframe -at focalLength -t 38 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 39 -v -29.828661917632392 $cameraTransform; setKeyframe -at translateY -t 39 -v 26.603514040444157 $cameraTransform; setKeyframe -at translateZ -t 39 -v 42.109420401571732 $cameraTransform; setKeyframe -at rotateX -t 39 -v -23.528127663805542 $cameraTransform; setKeyframe -at rotateY -t 39 -v -16.482808237044633 $cameraTransform; setKeyframe -at rotateZ -t 39 -v -12.372142404738851 $cameraTransform; setKeyframe -at focalLength -t 39 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 40 -v -30.805479303110012 $cameraTransform; setKeyframe -at translateY -t 40 -v 25.398701427872481 $cameraTransform; setKeyframe -at translateZ -t 40 -v 41.833421327197286 $cameraTransform; setKeyframe -at rotateX -t 40 -v -21.870302013298623 $cameraTransform; setKeyframe -at rotateY -t 40 -v -17.789565848045221 $cameraTransform; setKeyframe -at rotateZ -t 40 -v -12.701043094952734 $cameraTransform; setKeyframe -at focalLength -t 40 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 41 -v -31.684916216880826 $cameraTransform; setKeyframe -at translateY -t 41 -v 24.277665366008655 $cameraTransform; setKeyframe -at translateZ -t 41 -v 41.577177345305380 $cameraTransform; setKeyframe -at rotateX -t 41 -v -20.338427678861390 $cameraTransform; setKeyframe -at rotateY -t 41 -v -18.989231925866711 $cameraTransform; setKeyframe -at rotateZ -t 41 -v -13.031343767236082 $cameraTransform; setKeyframe -at focalLength -t 41 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 42 -v -32.468781789531327 $cameraTransform; setKeyframe -at translateY -t 42 -v 23.246390107873953 $cameraTransform; setKeyframe -at translateZ -t 42 -v 41.353232384702544 $cameraTransform; setKeyframe -at rotateX -t 42 -v -18.922799281626297 $cameraTransform; setKeyframe -at rotateY -t 42 -v -20.090434299302384 $cameraTransform; setKeyframe -at rotateZ -t 42 -v -13.332145437951590 $cameraTransform; setKeyframe -at focalLength -t 42 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 43 -v -33.141485348047006 $cameraTransform; setKeyframe -at translateY -t 43 -v 22.335517540424771 $cameraTransform; setKeyframe -at translateZ -t 43 -v 41.169291699715693 $cameraTransform; setKeyframe -at rotateX -t 43 -v -17.615808541529017 $cameraTransform; setKeyframe -at rotateY -t 43 -v -21.051857320470706 $cameraTransform; setKeyframe -at rotateZ -t 43 -v -13.609961917069722 $cameraTransform; setKeyframe -at focalLength -t 43 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 44 -v -33.698276514147622 $cameraTransform; setKeyframe -at translateY -t 44 -v 21.563737017991990 $cameraTransform; setKeyframe -at translateZ -t 44 -v 41.014953076563103 $cameraTransform; setKeyframe -at rotateX -t 44 -v -16.557114747600338 $cameraTransform; setKeyframe -at rotateY -t 44 -v -21.865800912349968 $cameraTransform; setKeyframe -at rotateZ -t 44 -v -13.834158781731471 $cameraTransform; setKeyframe -at focalLength -t 44 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 45 -v -34.139882982065025 $cameraTransform; setKeyframe -at translateY -t 45 -v 20.938345150626589 $cameraTransform; setKeyframe -at translateZ -t 45 -v 40.879042540259441 $cameraTransform; setKeyframe -at rotateX -t 45 -v -15.726160391473343 $cameraTransform; setKeyframe -at rotateY -t 45 -v -22.541253001150167 $cameraTransform; setKeyframe -at rotateZ -t 45 -v -13.974087210451158 $cameraTransform; setKeyframe -at focalLength -t 45 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 46 -v -34.457112235193364 $cameraTransform; setKeyframe -at translateY -t 46 -v 20.477217995156209 $cameraTransform; setKeyframe -at translateZ -t 46 -v 40.771512478322137 $cameraTransform; setKeyframe -at rotateX -t 46 -v -15.131891294223113 $cameraTransform; setKeyframe -at rotateY -t 46 -v -23.037884503267790 $cameraTransform; setKeyframe -at rotateZ -t 46 -v -14.072948513249990 $cameraTransform; setKeyframe -at focalLength -t 46 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 47 -v -34.670611992895488 $cameraTransform; setKeyframe -at translateY -t 47 -v 20.166873802756257 $cameraTransform; setKeyframe -at translateZ -t 47 -v 40.707191489602522 $cameraTransform; setKeyframe -at rotateX -t 47 -v -14.710921218961943 $cameraTransform; setKeyframe -at rotateY -t 47 -v -23.362970994500618 $cameraTransform; setKeyframe -at rotateZ -t 47 -v -14.156773662274901 $cameraTransform; setKeyframe -at focalLength -t 47 -v 13.712807770386641 $cameraShape;
setKeyframe -at translateX -t 48 -v -34.820960176814864 $cameraTransform; setKeyframe -at translateY -t 48 -v 19.956233701513703 $cameraTransform; setKeyframe -at translateZ -t 48 -v 40.681190613065922 $cameraTransform; setKeyframe -at rotateX -t 48 -v -14.344398665697774 $cameraTransform; setKeyframe -at rotateY -t 48 -v -23.553567687128002 $cameraTransform; setKeyframe -at rotateZ -t 48 -v -14.281524422253684 $cameraTransform; setKeyframe -at focalLength -t 48 -v 13.712807770386641 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_3_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_3_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation -79.193488232327155 75.878976897497722 114.842915481774330 $cameraTransform;
xform -rotation -30.630956582998699 -37.568424841915949 -24.788303136779973 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0001.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v -79.193488232327155 $cameraTransform; setKeyframe -at translateY -t 1 -v 75.878976897497722 $cameraTransform; setKeyframe -at translateZ -t 1 -v 114.842915481774330 $cameraTransform; setKeyframe -at rotateX -t 1 -v -30.630956582998699 $cameraTransform; setKeyframe -at rotateY -t 1 -v -37.568424841915949 $cameraTransform; setKeyframe -at rotateZ -t 1 -v -24.788303136779973 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_4_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_4_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation 30.680764331840585 96.915930796623513 105.219631292900960 $cameraTransform;
xform -rotation -41.104143706674542 16.831897871359466 13.392338845078770 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0012.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v 30.680764331840585 $cameraTransform; setKeyframe -at translateY -t 1 -v 96.915930796623513 $cameraTransform; setKeyframe -at translateZ -t 1 -v 105.219631292900960 $cameraTransform; setKeyframe -at rotateX -t 1 -v -41.104143706674542 $cameraTransform; setKeyframe -at rotateY -t 1 -v 16.831897871359466 $cameraTransform; setKeyframe -at rotateZ -t 1 -v 13.392338845078770 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_5_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_5_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation 58.601231460466472 -8.828163354930091 39.060556907132572 $cameraTransform;
xform -rotation -1.033820575866980 54.854933779059856 19.876854499856304 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0016.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v 58.601231460466472 $cameraTransform; setKeyframe -at translateY -t 1 -v -8.828163354930091 $cameraTransform; setKeyframe -at translateZ -t 1 -v 39.060556907132572 $cameraTransform; setKeyframe -at rotateX -t 1 -v -1.033820575866980 $cameraTransform; setKeyframe -at rotateY -t 1 -v 54.854933779059856 $cameraTransform; setKeyframe -at rotateZ -t 1 -v 19.876854499856304 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_6_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_6_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation 37.057430049361074 -29.190444560664154 38.355792521036378 $cameraTransform;
xform -rotation 23.697416245647215 31.012462129821419 11.036109411769621 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0020.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v 37.057430049361074 $cameraTransform; setKeyframe -at translateY -t 1 -v -29.190444560664154 $cameraTransform; setKeyframe -at translateZ -t 1 -v 38.355792521036378 $cameraTransform; setKeyframe -at rotateX -t 1 -v 23.697416245647215 $cameraTransform; setKeyframe -at rotateY -t 1 -v 31.012462129821419 $cameraTransform; setKeyframe -at rotateZ -t 1 -v 11.036109411769621 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_7_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_7_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation -41.118180573745519 -32.712966890810691 46.626684272070463 $cameraTransform;
xform -rotation 24.363607226398624 -46.707971331529940 -19.194146902754444 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0026.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v -41.118180573745519 $cameraTransform; setKeyframe -at translateY -t 1 -v -32.712966890810691 $cameraTransform; setKeyframe -at translateZ -t 1 -v 46.626684272070463 $cameraTransform; setKeyframe -at rotateX -t 1 -v 24.363607226398624 $cameraTransform; setKeyframe -at rotateY -t 1 -v -46.707971331529940 $cameraTransform; setKeyframe -at rotateZ -t 1 -v -19.194146902754444 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_8_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_8_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation -73.305811828305238 7.180258105666756 9.591670700897003 $cameraTransform;
xform -rotation -5.595503151988043 -88.498590071335371 -25.122598005578237 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0034.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v -73.305811828305238 $cameraTransform; setKeyframe -at translateY -t 1 -v 7.180258105666756 $cameraTransform; setKeyframe -at translateZ -t 1 -v 9.591670700897003 $cameraTransform; setKeyframe -at rotateX -t 1 -v -5.595503151988043 $cameraTransform; setKeyframe -at rotateY -t 1 -v -88.498590071335371 $cameraTransform; setKeyframe -at rotateZ -t 1 -v -25.122598005578237 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera seq_shot_0001_v001_cam_photos_LENSED_9_1...
string $cameraNodes[] = `camera -name "seq_shot_0001_v001_cam_photos_LENSED_9_1" -hfa 0.367559055118110  -vfa 0.735118110236220 -fl 11.171403013426557 -ncp 0.01 -fcp 10000 -shutterAngle 180 -ff "overscan"`;
string $cameraTransform = $cameraNodes[0];
string $cameraShape = $cameraNodes[1];
xform -zeroTransformPivots -rotateOrder zxy $cameraTransform;
setAttr ($cameraShape+".horizontalFilmOffset") -0.000000000000000;
setAttr ($cameraShape+".verticalFilmOffset") -0.000000000000000;
xform -translation 65.921510502852925 43.905374308103738 -17.819550921597177 $cameraTransform;
xform -rotation -52.205271325022188 93.954358036433192 36.743067227880630 $cameraTransform;
xform -scale 1 1 1 $cameraTransform;

// create image plane...
string $imagePlane = `createNode imagePlane`;
cameraImagePlaneUpdate ($cameraShape, $imagePlane);
setAttr ($imagePlane + ".offsetX") -0.000000000000000;
setAttr ($imagePlane + ".offsetY") -0.000000000000000;
setAttr ($imagePlane+".useFrameExtension") 0;
expression -n "frame_ext_expression" -s ($imagePlane+".frameExtension=frame");
setAttr ($imagePlane + ".imageName") -type "string" "c:/_store/dev/3DEtools-env/3DEtools/tests/maya/images/seq_shot_0001_v001/seq_shot_0001_v001_cam_photos_LENSED.0048.png";
setAttr ($imagePlane + ".fit") 4;
setAttr ($imagePlane + ".displayOnlyIfCurrent") 1;
setAttr ($imagePlane  + ".depth") (9000/2);

// parent camera to scene group...
parent $cameraTransform $sceneGroupName;
setAttr ($cameraTransform +".visibility") 0;
setKeyframe -at translateX -t 1 -v 65.921510502852925 $cameraTransform; setKeyframe -at translateY -t 1 -v 43.905374308103738 $cameraTransform; setKeyframe -at translateZ -t 1 -v -17.819550921597177 $cameraTransform; setKeyframe -at rotateX -t 1 -v -52.205271325022188 $cameraTransform; setKeyframe -at rotateY -t 1 -v 93.954358036433192 $cameraTransform; setKeyframe -at rotateZ -t 1 -v 36.743067227880630 $cameraTransform; setKeyframe -at focalLength -t 1 -v 11.171403013426557 $cameraShape;

// create camera point group...
string $pointGroupName = `group -em -name  "cameraPGroup_pgroup#1_1" -parent $sceneGroupName`;
$pointGroupName = ($sceneGroupName + "|" + $pointGroupName);


// create point p01...
string $locator = stringArrayToString(`spaceLocator -name p01`, "");
$locator = ("|" + $locator);
xform -t 43.489089145385364 25.790708012488032 8.604055695406771 $locator;
parent $locator $pointGroupName;

// create point p02...
string $locator = stringArrayToString(`spaceLocator -name p02`, "");
$locator = ("|" + $locator);
xform -t 5.520682481050132 -20.345734690979231 -15.011612438104038 $locator;
parent $locator $pointGroupName;

// create point p03...
string $locator = stringArrayToString(`spaceLocator -name p03`, "");
$locator = ("|" + $locator);
xform -t 11.321464980187864 10.751805198986268 -2.565613422594311 $locator;
parent $locator $pointGroupName;

// create point p04...
string $locator = stringArrayToString(`spaceLocator -name p04`, "");
$locator = ("|" + $locator);
xform -t 13.538208121528491 -1.046060654112761 -0.758525492229495 $locator;
parent $locator $pointGroupName;

// create point p05...
string $locator = stringArrayToString(`spaceLocator -name p05`, "");
$locator = ("|" + $locator);
xform -t -21.148271790648849 38.581753717654891 8.617630324652424 $locator;
parent $locator $pointGroupName;

// create point p06...
string $locator = stringArrayToString(`spaceLocator -name p06`, "");
$locator = ("|" + $locator);
xform -t -8.735045576928885 16.394002958935857 14.377404317803951 $locator;
parent $locator $pointGroupName;

// create point p07...
string $locator = stringArrayToString(`spaceLocator -name p07`, "");
$locator = ("|" + $locator);
xform -t -29.519001632564091 14.454080434423858 26.358921285537235 $locator;
parent $locator $pointGroupName;

// create point p08...
string $locator = stringArrayToString(`spaceLocator -name p08`, "");
$locator = ("|" + $locator);
xform -t -4.095433306241352 -7.708979019858024 18.040774797521749 $locator;
parent $locator $pointGroupName;

// create point p09...
string $locator = stringArrayToString(`spaceLocator -name p09`, "");
$locator = ("|" + $locator);
xform -t -25.359824145072182 -9.751471593412024 30.444110801652130 $locator;
parent $locator $pointGroupName;

// create point p10...
string $locator = stringArrayToString(`spaceLocator -name p10`, "");
$locator = ("|" + $locator);
xform -t -31.727712984687678 37.674986372025487 14.755263974942920 $locator;
parent $locator $pointGroupName;

// create point p11...
string $locator = stringArrayToString(`spaceLocator -name p11`, "");
$locator = ("|" + $locator);
xform -t 5.658701226114804 8.393070826231693 -12.963790290604891 $locator;
parent $locator $pointGroupName;

// create point p12...
string $locator = stringArrayToString(`spaceLocator -name p12`, "");
$locator = ("|" + $locator);
xform -t -37.021222048471692 5.252064676669882 25.482371189639082 $locator;
parent $locator $pointGroupName;

// create point p13...
string $locator = stringArrayToString(`spaceLocator -name p13`, "");
$locator = ("|" + $locator);
xform -t -41.494389741442646 8.771810504300504 5.744200963125223 $locator;
parent $locator $pointGroupName;

// create point p14...
string $locator = stringArrayToString(`spaceLocator -name p14`, "");
$locator = ("|" + $locator);
xform -t -20.078939296342114 10.980315412842273 -6.646300197200958 $locator;
parent $locator $pointGroupName;

// create point p15...
string $locator = stringArrayToString(`spaceLocator -name p15`, "");
$locator = ("|" + $locator);
xform -t 29.099103951697273 -31.109023777485191 8.217015137229396 $locator;
parent $locator $pointGroupName;

// create point p16...
string $locator = stringArrayToString(`spaceLocator -name p16`, "");
$locator = ("|" + $locator);
xform -t 1.072361898444733 5.549583218167143 4.517171672506095 $locator;
parent $locator $pointGroupName;

// create point p17...
string $locator = stringArrayToString(`spaceLocator -name p17`, "");
$locator = ("|" + $locator);
xform -t -15.878397574009499 -12.986323499764495 -2.986075955245838 $locator;
parent $locator $pointGroupName;

// create point p18...
string $locator = stringArrayToString(`spaceLocator -name p18`, "");
$locator = ("|" + $locator);
xform -t -0.207380676988075 -39.887023767682024 27.956232212863057 $locator;
parent $locator $pointGroupName;

// create point p20...
string $locator = stringArrayToString(`spaceLocator -name p20`, "");
$locator = ("|" + $locator);
xform -t 7.750483957681314 -3.623045977697146 -11.183344770555152 $locator;
parent $locator $pointGroupName;

// create point p22...
string $locator = stringArrayToString(`spaceLocator -name p22`, "");
$locator = ("|" + $locator);
xform -t -35.681476227825364 -43.103196012317703 38.431649411935467 $locator;
parent $locator $pointGroupName;

// create point p23...
string $locator = stringArrayToString(`spaceLocator -name p23`, "");
$locator = ("|" + $locator);
xform -t -4.932269755332664 -32.518935517444973 12.036144912945048 $locator;
parent $locator $pointGroupName;

// create point p24...
string $locator = stringArrayToString(`spaceLocator -name p24`, "");
$locator = ("|" + $locator);
xform -t 31.698440692508449 10.921049493380679 1.177202792310368 $locator;
parent $locator $pointGroupName;

// create point p25...
string $locator = stringArrayToString(`spaceLocator -name p25`, "");
$locator = ("|" + $locator);
xform -t 38.549687673253004 -6.886350269170251 11.146503436006412 $locator;
parent $locator $pointGroupName;

// create point p26...
string $locator = stringArrayToString(`spaceLocator -name p26`, "");
$locator = ("|" + $locator);
xform -t -40.766056114855203 -35.037321423427798 22.592967758451721 $locator;
parent $locator $pointGroupName;

// create point p27...
string $locator = stringArrayToString(`spaceLocator -name p27`, "");
$locator = ("|" + $locator);
xform -t 10.487080960438416 -26.912694078772844 -1.013147656289078 $locator;
parent $locator $pointGroupName;

// create point p28...
string $locator = stringArrayToString(`spaceLocator -name p28`, "");
$locator = ("|" + $locator);
xform -t 5.299115679749544 -19.461126298395602 -17.299590616723066 $locator;
parent $locator $pointGroupName;

// create point p29...
string $locator = stringArrayToString(`spaceLocator -name p29`, "");
$locator = ("|" + $locator);
xform -t -10.109031396533554 -24.899910727583478 -4.165425479102595 $locator;
parent $locator $pointGroupName;

// create point p30...
string $locator = stringArrayToString(`spaceLocator -name p30`, "");
$locator = ("|" + $locator);
xform -t -20.351273078410379 -12.713671446426739 -28.893434484825463 $locator;
parent $locator $pointGroupName;

// create point p31...
string $locator = stringArrayToString(`spaceLocator -name p31`, "");
$locator = ("|" + $locator);
xform -t 20.908982309124120 -14.007116003161311 -30.534813124572764 $locator;
parent $locator $pointGroupName;

// create point p32...
string $locator = stringArrayToString(`spaceLocator -name p32`, "");
$locator = ("|" + $locator);
xform -t 72.877266154846765 -4.483534378553546 -54.763651409467030 $locator;
parent $locator $pointGroupName;

// create point p33...
string $locator = stringArrayToString(`spaceLocator -name p33`, "");
$locator = ("|" + $locator);
xform -t -19.763812421483657 3.726773651604766 -20.549654433397421 $locator;
parent $locator $pointGroupName;

// create point p34...
string $locator = stringArrayToString(`spaceLocator -name p34`, "");
$locator = ("|" + $locator);
xform -t 73.268864667504502 10.327906942941432 -47.583651725967627 $locator;
parent $locator $pointGroupName;

// create point p35...
string $locator = stringArrayToString(`spaceLocator -name p35`, "");
$locator = ("|" + $locator);
xform -t 73.742382705824113 35.714949713140648 -35.263601747443971 $locator;
parent $locator $pointGroupName;

// create point p37...
string $locator = stringArrayToString(`spaceLocator -name p37`, "");
$locator = ("|" + $locator);
xform -t 73.995893343751391 60.984465934765069 -22.902124286814256 $locator;
parent $locator $pointGroupName;

// create point p38...
string $locator = stringArrayToString(`spaceLocator -name p38`, "");
$locator = ("|" + $locator);
xform -t 18.450616558104652 -10.048060739541153 -38.745419533463092 $locator;
parent $locator $pointGroupName;

// create point p39...
string $locator = stringArrayToString(`spaceLocator -name p39`, "");
$locator = ("|" + $locator);
xform -t 16.364700189181733 6.853060976596133 -30.999118335352193 $locator;
parent $locator $pointGroupName;

// create point p40...
string $locator = stringArrayToString(`spaceLocator -name p40`, "");
$locator = ("|" + $locator);
xform -t 17.041740686848161 32.517337453104794 -19.092775132572683 $locator;
parent $locator $pointGroupName;

// create point p41...
string $locator = stringArrayToString(`spaceLocator -name p41`, "");
$locator = ("|" + $locator);
xform -t 17.796542395510379 58.081430798626130 -6.734850179392481 $locator;
parent $locator $pointGroupName;

// create point p43...
string $locator = stringArrayToString(`spaceLocator -name p43`, "");
$locator = ("|" + $locator);
xform -t -9.199785277567203 55.269449057069735 0.549772963937130 $locator;
parent $locator $pointGroupName;

// create point p44...
string $locator = stringArrayToString(`spaceLocator -name p44`, "");
$locator = ("|" + $locator);
xform -t -36.753039511620344 52.644557093078674 7.724850481860500 $locator;
parent $locator $pointGroupName;

// create point p48...
string $locator = stringArrayToString(`spaceLocator -name p48`, "");
$locator = ("|" + $locator);
xform -t 39.899887147464717 -37.560445457809529 18.938055419286115 $locator;
parent $locator $pointGroupName;

// create point p49...
string $locator = stringArrayToString(`spaceLocator -name p49`, "");
$locator = ("|" + $locator);
xform -t -22.933825431506421 -34.070861285425245 17.116386198753588 $locator;
parent $locator $pointGroupName;

// create point p50...
string $locator = stringArrayToString(`spaceLocator -name p50`, "");
$locator = ("|" + $locator);
xform -t -10.003474279452059 29.873641253284298 -11.424933093243510 $locator;
parent $locator $pointGroupName;

// create point p51...
string $locator = stringArrayToString(`spaceLocator -name p51`, "");
$locator = ("|" + $locator);
xform -t 84.362678807527843 50.899067593447114 0.588291664695589 $locator;
parent $locator $pointGroupName;

// create point p53...
string $locator = stringArrayToString(`spaceLocator -name p53`, "");
$locator = ("|" + $locator);
xform -t 18.279005632839606 74.834141365360367 1.137853569840758 $locator;
parent $locator $pointGroupName;

// create point p54...
string $locator = stringArrayToString(`spaceLocator -name p54`, "");
$locator = ("|" + $locator);
xform -t -30.634936016082861 -51.221712342455220 54.239067988681981 $locator;
parent $locator $pointGroupName;

// create point p55...
string $locator = stringArrayToString(`spaceLocator -name p55`, "");
$locator = ("|" + $locator);
xform -t 5.228204465519534 -48.188346079097414 44.495021564546192 $locator;
parent $locator $pointGroupName;

// create point p56...
string $locator = stringArrayToString(`spaceLocator -name p56`, "");
$locator = ("|" + $locator);
xform -t -37.583443344586406 34.962307884900923 4.162123881285339 $locator;
parent $locator $pointGroupName;

// create point p57...
string $locator = stringArrayToString(`spaceLocator -name p57`, "");
$locator = ("|" + $locator);
xform -t 40.955426048857888 -44.079383228752455 35.181047422345046 $locator;
parent $locator $pointGroupName;

// create point p58...
string $locator = stringArrayToString(`spaceLocator -name p58`, "");
$locator = ("|" + $locator);
xform -t 22.024462809508442 -13.210682773384779 -2.170550898145081 $locator;
parent $locator $pointGroupName;

// create point p59...
string $locator = stringArrayToString(`spaceLocator -name p59`, "");
$locator = ("|" + $locator);
xform -t 30.369519674302985 -3.179950937810485 2.861203719064690 $locator;
parent $locator $pointGroupName;

// create point p60...
string $locator = stringArrayToString(`spaceLocator -name p60`, "");
$locator = ("|" + $locator);
xform -t -17.586991122672494 6.569392275650907 21.957363100700157 $locator;
parent $locator $pointGroupName;

xform -zeroTransformPivots -rotateOrder zxy -scale 1.000000 1.000000 1.000000 $pointGroupName;

xform -zeroTransformPivots -rotateOrder zxy -translation 0.000000000000000 0.000000000000000 0.000000000000000 -scale 1.000000000000000 1.000000000000000 1.000000000000000 -rotation -0.000000000000000 0.000000000000000 0.000000000000000 $sceneGroupName;


